on:
  push:
    branches:
      - main

name: Build java image

jobs:
  build-and-push-java-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_USER_TOKEN }}
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerRegistry ghrc
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_USER }}
          password: ${{ secrets.CI_USER_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/vigen-s/java-images/challenge_ww_backend:latest
            ghcr.io/vigen-s/java-images/challenge_ww_backend:${{ steps.date.outputs.date }}
          no-cache: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.CI_USER_TOKEN }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}